README.md

small fix for `npm install` docs

[minor fix] install

---

.travis.yml

Just needs to be enabled on travis site.

[ci] add travis

---

package.json
test/common.js

10 seconds is too short and the tests were timing out

Increase `test-integration` timeout to 30 seconds

---

README.md
package.json
test/common.js

1. Add a pointer to minikube for integration testing.
2. Better retry loop for cleaning up namespaces.

Document testing, improve integration test infrastructure.

---

lib/common.js

* configmaps (aka 'cm')
* deployments (aka 'deploy')
* endpoints (aka 'ep')

fix(aliases): Add missing object aliases

---

lib/common.js
lib/extensions.js
lib/namespaces.js

Support extensions/v1beta1.ReplicaSet

---

README.md
lib/index.js
lib/third-party-resources.js
test/common.js
test/third-party-resources.test.js

Add the ability to create a ThirdPartyResources API object and add resource
objects to it.
Closes #43

feat(ThirdPartyResources): add support for Third Party Resources

---

README.md

docs(bugos): Fix shameful "k8" usage

---

lib/api.js
lib/apps.js
lib/batch.js
lib/common.js
lib/index.js
lib/namespaces.js
lib/rbac.js
test/apps.test.js
test/batch.test.js
test/common.js
test/rbac.test.js

Updated version of https://github.com/godaddy/kubernetes-client/pull/57
Closes: https://github.com/godaddy/kubernetes-client/issues/66
Closes: https://github.com/godaddy/kubernetes-client/issues/53

feat(Support for more APIs): Apps, Batch, and RBAC

---

test/api-group.test.js
test/base.test.js

[1]:https://github.com/godaddy/kubernetes-client/issues/90

test(matchLabels): add test for bug reported in [1]

---

.eslintrc
lib/api.js
lib/config.js
lib/replicationcontrollers.js
package.json
test/common.js
test/config.test.js
test/third-party-resources.test.js

* Do a lint pass; and
* add lint checks to the test script.

refactor(linter): Upgrade godaddy-style

---

lib/api-group.js
lib/apps.js
lib/batch.js
lib/core.js
lib/extensions.js
lib/namespaces.js
lib/rbac.js
lib/third-party-resources.js
test/namespaces.test.js

refactor(namespaces): specify name spaced resources explicitly

---

lib/api-group.js
lib/base.js
package.json
test/pods.test.js

Allows specifying these patch opertions: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#patch-operations

feat(Support for user-specified PATCH operations)

---

README.md

this would have saved me a lot of time.  :)

README.md: query parameters list example

---

README.md

docs(README.md): Document label selector filtering limitations.

---

lib/config.js
test/config.test.js

Immutable version, Closes #153, #154

fix: accept relative and absolute paths

---

lib/api-group.js
package-lock.json
package.json

lodash.merge is better documented and well-known.

refactor(options merging): use lodash.merge instead of assign-deep.

---

package-lock.json
package.json

https://nvd.nist.gov/vuln/detail/CVE-2017-17461
https://nvd.nist.gov/vuln/detail/CVE-2017-1000427

chore(upgrade deps): avoid potential vulnerabilities.

---

package.json

chore(package): update @types/node to version 9.4.2

---

README.md
lib/swagger-client.js
package-lock.json
test/swagger-client.test.js

Converts a Swagger spec into a kubernetes-client API client.
https://github.com/godaddy/kubernetes-client/issues/129

feat(Swagger): experimental support for Swagger.

---

.travis.yml

https://www.npmjs.com/package/greenkeeper-lockfile#setup

fix(greenkeeper): updating package-lock.json requires npm@5 or later

---

lib/swagger-client.js
test/swagger-client.test.js

Related: https://github.com/godaddy/kubernetes-client/issues/199

feat(getStream): add support for getStream to swagger-based client code

---

lib/swagger-client.js

This change facilitates support for CRDs.

refactor(swagger-client): add `._addSpec` logic

---

package.json

chore(package): update assume to version 2.0.1

---

lib/swagger-client.js
test/swagger-client.test.js

Throw an Error if status code from HTTP is not 2XX.

fix(error handling): replicate pre-5.0.0 error handling

---

typings/index.d.ts

Added missing return types for the functions in the typings.

Fix return types for functions in typings

---

examples/basic.js

Adds additional examples to assist with patching knowledge

---

.gitignore
lib/auth-providers/cmd.js
lib/auth-providers/openid.js
lib/config.js
lib/request.js
package-lock.json
package.json
test/config.test.js

Implements a semi-standardized way of implementing `auth-providers` and refreshes authentication on-demand (i.e 401)
Fixes #184.

WIP: Support GKE and OpenID Authentication

---

README.md
examples/watch.js

docs(examples): add an example for streaming events from a watch endpoint

---

README.md
examples/deployment-create-patch-rollback.js

Example in response to issue #204 
This creates a deployment, patches it with a new version of an image, and rolls back to the original image.

feat(example): example for creating, updating, and rolling back a deployment

---

examples/apply-deploy.js
lib/swagger-client.js
test/swagger-client.test.js

Ref https://github.com/godaddy/kubernetes-client/issues/215

feat(CRDs): add Cluster scope support

---

package.json
scripts/templates/ts-interface.mustache
scripts/templates/ts-namespace.mustache
scripts/typings.js

This is the first PR that begins to address https://github.com/godaddy/kubernetes-client/issues/249

feat(typings): script to generate declaration file for current API

---

lib/index.js
lib/swagger-client.js
test/swagger-client.test.js

The next step is to add a TypeScript declaration file for this specific API
version.

feat(Client1_10): add Client class for a specific API version

---

lib/request.js

fixes https://github.com/godaddy/kubernetes-client/issues/264

Fix unhandled promise rejection caused by failed auth refresh

---

lib/request.js

cc https://github.com/godaddy/kubernetes-client/issues/328

fix(auth): update auth settings after refreshing

---

examples/timeout.js
lib/request.js

Fixes https://github.com/godaddy/kubernetes-client/issues/328

feat(timeout): plumb a timeout option for HTTP requests

---

lib/swagger-client.js

cc https://github.com/godaddy/kubernetes-client/issues/352

chore(loadSpec): copy from fluent-openapi

---

README.md

Modify documentation to explain config more thoroughly

---

lib/request.js
lib/swagger-client.js

Remove authentication from /openapi/v2 call

---

package-lock.json
package.json

It addresses https://snyk.io/vuln/SNYK-JS-LODASHMERGE-173732

chore(upgrade): swagger-fluent to ^3.1.2

---

examples/vpa/using-crds-vpa.js
examples/vpa/vpa-crd.json

Add vpa specific example of crd usage

---

examples/watch.js

Closes https://github.com/godaddy/kubernetes-client/issues/432

docs(example): fix examples/watch.js

---

README.md

Closes https://github.com/godaddy/kubernetes-client/issues/444

docs(README.md): clarify .loadSpec() support

---

package.json

Closes https://github.com/godaddy/kubernetes-client/issues/452

chore(upgrade): swagger-fluent@3.1.3

---

examples/kubernetes-client-node.js
lib/backends/kubernetes-client-node.js
lib/backends/kubernetes-client-node.test.js
package-lock.json
package.json

Experimental support for a @kubernetes/client-node based backend.

feat(backends): @kubernetes/client-node

---

backends/request/client.js

See https://github.com/godaddy/kubernetes-client/issues/493

chore(.getWebSocket): stub Request backend

---

package-lock.json
package.json

Fixes https://github.com/godaddy/kubernetes-client/issues/518

chore(openid-client): downgrade to 2.5.0

---

lib/swagger-client.js

Fixes https://github.com/godaddy/kubernetes-client/issues/517

fix(getObjectStream): for CRDs

---

.travis.yml
package-lock.json
package.json
typings/index.d.ts

BREAKING CHANGE 8 is out of maintenance.

chore: drop support for node 8 at support for 12
