- lib/api.js
- test/api.test.js
- test/objects.test.js
This removes the default namespace shortcuts (e.g., `api.rc`) because they're
ambiguous with the cluster level resources.
> Cluster level resources, for example, `k8.resourcequotas.get`

- lib/replicationcontrollers.js
- test/objects.test.js
`rc.po.get` breaks usual pattern (if no options, get everything), because it's
not useful do that (users should use `po.get`), and we don't handle it in the
`rc.po.get` code. It's a programming mistake of `options` is missing, so throw
an Error.
> Throw an Error if `rc.po.get` invoked without options and cb.

- package.json
- test/api.test.js
- test/common.js
The time it takes to remove a namespace seems highly variable. Provide an
environment variable to configure it:
`TIMEOUT=120000 NAMESPACE=integration-tests-sbw URL=https://my-cluster.com npm run test-integration`
> test-integration: make timeout configurable

- lib/api-group.js
- lib/core.js
- lib/extensions.js
- test/api-group.test.js
"Group" is terminology from: https://github.com/kubernetes/kubernetes/blob/master/docs/api.md
> Rename `Api` to `ApiGroup`

- lib/api-group.js
- lib/base.js
- lib/namespaces.js
- lib/pods.js
- lib/replicationcontrollers.js
Before this change our constructors for ReplicationControllers, Pods, and
Namespaces had different APIs than the BaseObject. This fixes the mismatch.
> Ensure API for Kubernetes objects is consistent.

- README.md
- lib/api.js
- test/api.test.js
E.g.,
```
const api = new Api(...);
api.core.ns.po.get(...);
api.group('extensions/v1beta1').ns.deployments.get(...);
api.group(manifest).ns.kind(manifest).post(...);
```
> Add a wrapper for switching API clients

- README.md
- lib/api-group.js
- lib/common.js
- test/api-group.test.js
- test/common.js
The `kind` method was not bound correctly and would throw an error stating that `kind` was not a function. I also noticed an issues where resources that ended in `es` were not being aliased to their singular version correctly. An example is `ingresses` would alias to `ingresse`.
> Fixed an issue with aliasing and `kind` error

- lib/common.js
Without this change I was unable to create/modify persistent volumes.
> Add a name for PersistentVolumes/PVs

- README.md
- lib/base.js
- lib/pods.js
- test/common.js
- test/objects.test.js
- test/pods.test.js
There are several objects/entities that are namespaced by Kubernetes objects.
`/api/v1/namespaces/{namespace}/pods/{name}/log` is an obvious one, but there's
more. For example:
* Proxy objects (e.g., `/api/v1/namespaces/{namespace}/services/{name}/proxy/`)
* Deployment related objects (e.g., `/apis/extensions/v1beta1/namespaces/{namespace}/deployments/{name}/rollback`)
* ...
This PR implements a story for handling these cases and changes the
documentation to encourage users to use namespaced functionality by default
(e.g., `api.ns.po('foo').get(print)` vs `api.ns.po.get(foo, print)`).
> Add namespaced support to objects other than `namespaces`

- test/api-group.test.js
- test/common.js
- test/extensions.test.js
- test/objects.test.js
- test/pods.test.js
Each time we need a fresh namespace, generate a new name, instead of recycling
(deleting and re-creating) a single name. Removing a namespace isn't
synchronous and can be stuck in 'Terminating' for a while, especially on
minikube. That resulted in timeouts, or very long running tests.
> Improve integration testing framework to give more consistent results

- package.json
> chore(changelog): Use `standard-version` for managing CHANGELOG.md

- lib/base.js
One example is 401 "Unauthorized\n".
> fix(error handling): handle API errors that aren't JSON

- lib/api-group.js
- lib/namespaces.js
The BaseObject is callable by default, so the original "namespacer" hack is
superfluous. See d083f93be23182f4a629c02cdd319692a09168f8.
> chore(remove old code): remove old "namespacer" code

- lib/namespaces.js
- test/namespaces.test.js
`.addResource` adds a resource to the default namespace
(i.e., `api.core.ns.newResource`) and ensures the resource is passed to the
named namespaces (i.e., `api.core.ns('foo').newResource`).  The intended use
case case for `.addResource` is with ThirdPartyResource defined objects.
> refactor(Namespaces): implement `.addResource`

- test/common.js
VERSION was cruft: it didn't work well, was only partially implemented.
> refactor(testing): drop "support" for passing VERSION to integration tests

- test/common.js
This refactor makes it easier to add new API objects to the test framework.
This is an update of https://github.com/godaddy/kubernetes-client/pull/59
> Reduce duplicated code in test/common.js

- lib/config.js
- test/config.test.js
The ca.crt file inside a pod is the 'certificate authority', not a 'client certificate'.
---
This should fix errors 'unable to verify the first certificate' when using the in-cluster configuration.
> Use ca.crt correctly

- lib/api-group.js
- package.json
- test/pods.test.js
Use `json: true` with request: request has more robust `content-type` checking.
> fix(response `content-type` checking): more robust JSON response handling

- lib/base.js
[1] changed BaseObject so that its properties were no longer a
superset of the `options` BaseObject construtor argument (specifically
removing the `name` property). That broke `.match()` and
`.matchLabels()` which depended on that property.
Fixes: #90
[1]:https://github.com/godaddy/kubernetes-client/commit/d083f93be23182f4a629c02cdd319692a09168f8#diff-86b75ecfbd25aa771c8e9e0dff8eb00fL25
> fix(matchLabels): call BaseObject constructor with correct arguments

- lib/api-group.js
- lib/apps.js
- lib/batch.js
- lib/core.js
- lib/extensions.js
- lib/rbac.js
- lib/third-party-resources.js
- test/api-group.test.js
- test/third-party-resources.test.js
The current code assumes every root group resources (e.g., /api/v1/nodes) is a
BaseObject. This adds support for custom resources (e.g., Pod or Deployment).
This is groundwork for:
https://github.com/godaddy/kubernetes-client/issues/47
> refactor(ApiGroup): support custom root group resources

- lib/container-base-object.js
- lib/pods.js
- test/container-base-object.test.js
Some named resources (e.g., `pod('foo'))` can contain resources (e.g.,
`pod('foo').log` or `deploy('bar').status`). The ContainerBaseObject makes
implementing these resources easier.
This is groundwork for https://github.com/godaddy/kubernetes-client/issues/47.
> refactor(BaseObject): add a `ContainerBaseObject` to facilitate named resources

- CONTRIBUTING.md
Fixes https://github.com/godaddy/kubernetes-client/issues/81
cc https://github.com/godaddy/kubernetes-client/issues/105
> docs(CONTRIBUTING.md)

- lib/config.js
- test/config.test.js
Using kubectl 1.6.4 client against Google Container Engine
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.7", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"clean", BuildDate:"2017-04-27T09:42:05Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```
produces a different data structure in ~/.kube/config
```
- name: context-name
user:
auth-provider:
config:
access-token: token
cmd-args: config config-helper --format=json
cmd-path: /home/foo/google-cloud-sdk/bin/gcloud
expiry: …
```
> support for auth-provider access-token in fromKubeconfig()

- lib/base.js
This fixes stream calls without an `options` argument.  E.g.,:
```
// This used to TypeError.
// Now it returns a stream.
const stream = core.ns.po.get();
```
https://github.com/godaddy/kubernetes-client/issues/37#issuecomment-259434515
> fix(undefined `options` passed to `.get`): set default `options` value to `{}`

- README.md
README does not show proper use of `delete` method. Possibly caused confusion with how to use the method (see #120).
> fix(Update README.md): Show correct delete usage

- README.md
- lib/base.js
- test/pods.test.js
This change facilitates a Promised-based API (see [1] for discussion). The
original `request`-like behavior is unchanged: return a stream if the caller
omits a callback.
[1]: https://github.com/godaddy/kubernetes-client/issues/37
> feat(Add `getStream` to resource API)

- lib/apps.js
- test/apps.test.js
Hey, are you interested in a PR for adding deployments under `apps` ? If so, I'll see about adding tests and all to this as well instead of just a one-liner. It looks like [apps/v1beta1.Deployment](https://github.com/kubernetes/kubernetes.github.io/pull/3814#issuecomment-303239179) "will eventually be the default," and is working that way in 1.6, but for the time being deployments are under both extensions and apps. 
I've only just started using this client library, and I know it's hard to support multiple versions at once, so I understand if you've got other concerns that would discourage this PR. Thanks!
> feat(Deployments): Support apps/deployments

- lib/base.js
- test/base.test.js
Some kubernetes api's requires to send body within delete request.
Examples: [job deletion](https://kubernetes.io/docs/api-reference/v1.7/#delete-41) and [pod deletion](https://kubernetes.io/docs/api-reference/v1.7/#delete-58)
I needed to send DeleteOptions in request body to make job deletion also to delete all related pods.
Changes in this pull request provides possibility to do this in same way, as it works for POSTs.
````
const K8s = require('kubernetes-client');
const batch = new K8s.Batch({/*add configuration*/});
batch.namespaces('default').jobs.delete({
name: 'some-job',
body: {
kind: 'DeleteOptions',
apiVersion: 'batch/v1',
propagationPolicy: 'Foreground'
}
}, (err, data) => console.log(err, data))
````
> Make possible to send body in delete requests

- README.md
- lib/api-group.js
- lib/base.js
- lib/replicationcontrollers.js
- package.json
- test/common.js
- test/container-base-object.test.js
- test/namespaces.test.js
- test/objects.test.js
- test/promise.test.js
This preserves the original callback-based "core" implementation and layers the
promised-based API on top of that core implementation. The goal is start using
and iterating on the promised-based API even if we expect the underlying
implementation to evolve (e.g., we could consider replacing the core
callback-based implementation with a promise one).  See
https://github.com/godaddy/kubernetes-client/issues/37 for discussion.
Example usage:
```js
const core = new api.Core({
url: 'http://my-k8s-api-server.com',
promises: true
});
async function main() {
try {
const pods = await core.ns('kube-system').po.get();
console.log(`Watching: ${ JSON.stringify(pods, null, 2) }`);
const stream = core.ns('kube-system').po.getStream({ qs: { watch: true }});
stream.on('data', data => { …
```
> feat(Promise API): Experimental support for a promise-based API

- lib/api-group.js
- lib/request.js
- package-lock.json
This refactor isn't useful by itself, but is part of the larger effort to
generate API clients based on swagger docs:
https://github.com/godaddy/kubernetes-client/issues/129
Forthcoming PRs will leverage this change.
> refactor(request): move REST request code to it's own file.

- package-lock.json
- package.json
- typings/index.d.ts
- typings/index.test.ts
- typings/tsconfig.json
Initial cut at TypeScript support for `kubernetes-client`. 
This does not include good support for third-party resources or the beta `promises` feature. Resolves https://github.com/godaddy/kubernetes-client/issues/131
> feat(TypeScript): Initial cut at TypeScript support.

- README.md
- lib/replicationcontrollers.js
- test/objects.test.js
BREAKING CHANGE: The convenience function for selecting replicationcontroller
pods doesn't follow the kubernetes-client API contract. We're removing it
because it's cumbersome to support with recent changes (*e.g.*, support for
promises and the swagger gen code).
> chore(ReplicationController): remove replicationcontrollers.pods feature

- README.md
- lib/base.js
- package-lock.json
- package.json
- test/common.js
- test/promise.test.js
Resolves #189
BREAKING CHANGE: This removes the (deprecated) `request`-like behavior of
returning a stream when the caller omits a callback. Use `.getStream` (instead
of `.get` without a callback) to get a stream.
> feat(promises): if caller doesn't specify a callback, return a promise

- README.md
- lib/custom-resource-definitions.js
- lib/namespaces.js
- lib/third-party-resources.js
- test/api-group.test.js
- test/apps.test.js
- test/base.test.js
- test/batch.test.js
- test/common.js
- test/custom-resource-definition.test.js
- test/deployments.test.js
- test/extensions.test.js
- test/namespaces.test.js
- test/objects.test.js
- test/pods.test.js
- test/promise.test.js
- test/rbac.test.js
- test/third-party-resources.test.js
Fixes #187
BREAKING CHANGE: Removes default namespace feature. With a default namespace,
`api.namespaces.get` is potentially ambiguous: get the default namespaces or
get all namespaces. Remove the default namespace to be consistent with other
code.
> fix(namespaces): api.namespaces('foo') usage

- lib/pods.js
- test/pods.test.js
BREAKING CHANGE: `pods.log` doesn't follow the kubernetes-client API
conventions. Replace uses of `pods.log('foo')` with `pods('foo').log.get()`.
> chore(pods.log): remove the deprecated `pods.log` function.

- lib/api-group.js
- test/api-group.test.js
The readme indicates that bare request options can be passed through when instantiating ApiGroup objects. It looks like there was a regression introduced with https://github.com/godaddy/kubernetes-client/pull/161. I've included a fix here, along with tests for all of the parameters defined in the docs.
> Fix request options parsing in ApiGroup

- .travis.yml
- package.json
BREAKING CHANGE: EOL for 4 is end of April (https://github.com/nodejs/Release).
We're dropping support a little early in order to leverage some 6+ features for
upcoming improvements (e.g., https://github.com/godaddy/kubernetes-client/pull/207)
> chore(Node.js support): Drop support for Node.js 4 and 5

- examples/canary-controller.js
- lib/config.js
- test/config.test.js
- test/fixtures/kube-fixture.yml
Talked with @jcrugzz, we probably need a back patch for this fix (probably for version 4?) since `trimmer` is still using 3.x.x version.
> Automatically load kubeconfig when its provided as a path to the file

- .travis.yml
Travis uses `npm ci` by default for pull request builds. npm ci won't work
with greenkeeper pull requests because:
> If dependencies in the package lock do not match those in
> package.json, npm ci will exit with an error, instead of updating the
> package lock.
Tell travis to run `npm install` instead.
https://github.com/greenkeeperio/greenkeeper-lockfile#npm
> chore(travis): always use `npm install`

- lib/config.js
**NOTE**
Do we eventually want to support multiple config files in the future?
https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#create-a-second-configuration-file
> fix(kube-config): use KUBECONFIG env var if set

- lib/config.js
- package-lock.json
- package.json
- test/config.test.js
- test/fixtures/kube-fixture-two.yml
Adding support for multiple config files in `KUBECONFIG` env variable.
Official ref: https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#create-a-second-configuration-file
Output of `console.log(yaml.dump(merge.all(configs)))` ([ref to configs](https://github.com/godaddy/kubernetes-client/pull/326/files#diff-f7bf2b665273dfa66ffa4ad7c0a52bb9R183)) is:
which matches the output of `kubectl config view`:
> feat(config): support multiple config files in KUBECONFIG

- lib/swagger-client.js
- package-lock.json
- scripts/templates/ts-interface.mustache
- typings/index.d.ts
- Fix #334 - Add method `addCustomResourceDefinition` to the typings.
- Add `.../status` and `.../scale` endpoints to CRD swagger definition as specified in the Kubernetes API
> Fix missing addCustomResourceDefinition in type definitions, add support for /status and /scale CRD endpoints

- lib/config.js
- test/config.test.js
this fixes #350 by making sure `user.exec.env` and `user.exec.args` are defined before using them when creating a config with `user.exec`.
> handle optional kube config user exec properties

- lib/swagger-client.js
- package-lock.json
- test/swagger-client.test.js
According to this Kubernetes doc:
https://kubernetes.io/docs/concepts/overview/kubernetes-api/#openapi-and-swagger-definitions
The `/swagger*` endpoints have been deprecated starting with v1.10.
This commit changes `loadSpec` to address this:
1. Initially attempts to contact `/openapi/v2` with `Accept: application/json` in order
to get the swagger file via the new URL
2. If that fails with a 404, attempts to contact `swagger.json` to support clusters which
do not have the new endpoint
fixes #352
> Change the endpoint called by loadSpec

- lib/swagger-client.js
- test/swagger-client.test.js
Previously, only a 404 on /openapi/v2 would cause a fallback
to the /swagger.json endpoint. Now, ALL error codes from /openapi/v2
cause a fallback to swagger.json
fixes #363
> Fallback to old swagger.json endpoint

- lib/request.js
- test/request.test.js
Fixes https://github.com/godaddy/kubernetes-client/issues/376
> fix(request): handle 200 responses with an empty body

- lib/config.js
> Allow passing relative root  when running inCluster

- lib/alias.js
/api is an endpoint, so we shouldn't alias /apis to /api.
Fixes https://github.com/godaddy/kubernetes-client/issues/391
> fix(aliasing): don't alias apis (to api)

- lib/swagger-client.js
The /openapi/v2 endpoint is protected by authentication. Also reported by one of my downstream user on https://github.com/wongnai/kube-slack/issues/50
I'm not sure why this call was flagged with noAuth?
> swagger-client: Remove noAuth

- scripts/templates/ts-interface.mustache
- typings/index.d.ts
- typings/index.test.ts
kubernetes-client exposes a declaration file for a specific version of the
Kubernetes API. It's not useful to load the API client at runtime.
Closes https://github.com/godaddy/kubernetes-client/issues/400
> fix(typings): remove `.loadSpec()` from declarations

- README.md
Closes https://github.com/godaddy/kubernetes-client/issues/407
> docs(kubeconfig): document context option to `fromKubeconfig`

- lib/index.js
- lib/swagger-client.js
getNames is used to setup alias's for the client.  This would allow someone to specify their own aliases.  This relates to #418
This PR should replace #420 
The changes here are much more minimal than the previous changes.
@silasbw let me know what you think
> feat:  ability for a user to specify their own getNames funciton.

- lib/backends/request.js
One of the endpoints we have in openshift, "initiatebinary", allows someone to upload a tar archive to openshift as part of there build.  In order to make it work with request, you have to specify the json option to be false.
Currently the default options in the `http` method have the json value set to true with no way to change it.  
This PR adds the ability to change that value to false if needed.
> feat: have the ability to make the request json option false

- package-lock.json
- package.json
npm has reported denial of service vulnerability that's affecting versions of `js-yaml` before 3.13.0.  This caused `npm audit` to fail on our modules that rely on `kubernetes-client`. 
There is an explanation of the vulnerability on this advisory: https://www.npmjs.com/advisories/788
This PR bumps the version of `js-yaml` as per the advisory's recommendation.
> Updated js-yaml to 3.13.0 to patch npm vulnerability in advisory 788

- lib/config.js
This adds the current namespace to the return value of the `fromKubeconfig` function.   I noticed this value is also returned in the `getInCluster` function.
In our openshift node client([nodeshift](https://github.com/nodeshift/nodeshift)), we us the current namespace(project in openshift terms) the user is logged into.  I can derive it from calling `loadKubeconfig` and then parsing the current context from the loaded config, but that makes an extra call to look up the configuration.
It is more of a convenience thing and i would hate to clutter the returned object, so wanted to see your thoughts
Thanks
> feat: expose the current namespace on the config object

- lib/swagger-client.js
- lib/swagger-client.test.js
Currently, URLs for namespaced watches for CRD
objects are incorrectly formatted (the result instead
tries to do a GET on a CRD named `watch`), causing k8s to
return a 404.
This patch corrects this issue
Fixes #468
> fix(CRDs): malformed watch paths for namespaced CRDs

- backends/request/client.js
Looks like after moving the backends, this path needs to be updated to be able to perform the relative import
using the code:
```
const Client = require('kubernetes-client').Client;
const Request = require('kubernetes-client/backends/request');
const backend = new Request(Request.config.fromKubeconfig());
const client = new Client({ backend, version: '1.13' });
await client.loadSpec();
```
i get this error
```
Error: Failed to get /openapi/v2 and /swagger.json: Cannot find module '../auth-providers/cmd.js'
Require stack:
- /Users/rsim/zendesk/scooter-ui/node_modules/kubernetes-client/backends/request/client.js
- /Users/rsim/zendesk/scooter-ui/node_modules/kubernetes-client/backends/request/index.js
- /Users/rsim/zendesk/scooter-ui/node_modules/kubernetes-client/lib/swagger-client.js
- …
```
> Update auth-provider path

- examples/crontabs-crd.json
- examples/deploymentnotifier-crd.json
- examples/vpa/vpa-crd.json
- lib/swagger-client.js
- lib/swagger-client.test.js
Currently, it's only possible to specify one api
version for CRD objects via the deprecated
`version` field when building their spec paths.
This commit adds support for building spec paths
for multiple CRD versions specified in the
`versions` list while maintaining compatibility
with `version`.
Fixes #458
> fix(CRDs): Use `versions` list for spec paths

- merging-with-kubernetes.md
The end comment was reveresed, so it was commenting out things that should not have been commented out
> doc: fix merge with kube doc.

- README.md
`import * as Api from 'kubernetes-client';
`
will print a warning in console for newer versions: 
> deprecated require('kubernetes-client').config, use require('kubernetes-client/backends/request').config
> Docs: Typescript Example Fix

- backends/request/client.js
Exec request throws 403 error.
Exec failing route : `api.v1.namespaces(NAMESPACE).pods(PODNAME).exec.post()`.
`ws` seems to only supports authorization header for token authentication which is not passed to `ws` instance. Please see this [answer](https://github.com/godaddy/kubernetes-client/issues/346#issuecomment-489602443) for more details.
The [issue](https://github.com/godaddy/kubernetes-client/issues/346#issuecomment-489602443).
I hope it helps :)
> Add quick fix for 403 throws on pod-exec
